controller_list:
  - name: fake_gripper_group_controller
    type: interpolate
    rate: 60
    joints:
      - simple_gripper_right_driver_joint
  - name: fake_arm_group_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6